Repository Nagel29/rancid-tomatillos, pull requests merged in 2022-12, with the labels that each got.

#8 add basic detail page and user flow
  src/App.css
  src/App.js
  src/App.test.js
  src/components/App/App.js
  src/components/Card/Card.js
  src/components/Details/Details.css
  src/components/Details/Details.js
  src/components/MoviesCardsContainer/MoviesCardsContainer.js
  src/index.js
  src/movieData.js
Labels: enhancement

#10 Feature/network requests
  src/apiCalls.js
  src/components/App/App.js
  src/movieData.js
Labels: enhancement

#19 Feature/style all movies
  src/components/App/App.css
  src/components/App/App.js
  src/components/Card/Card.css
  src/components/Card/Card.js
  src/components/MoviesCardsContainer/MoviesCardsContainer.css
  src/components/MoviesCardsContainer/MoviesCardsContainer.js
  src/images/ripe-tomatillo.png
  src/images/rotten-tomatillos.webp
  src/images/spoiled-tomatillo.png
  src/index.css
  src/logo.svg
Labels: enhancement

#14 Make all movies display alphabetical
  src/components/App/App.js
Labels: enhancement

#26 Feature/cypress tests
  cypress.config.js
  cypress/e2e/all_movies_spec.cy.js
  cypress/e2e/movie_deatils_spec.cy.js
  cypress/fixtures/example.json
  cypress/fixtures/money_plane.json
  cypress/fixtures/movies.json
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
  src/apiCalls.js
  src/components/App/App.js
  src/components/Card/Card.js
  src/components/Details/Details.js
  src/components/MoviesCardsContainer/MoviesCardsContainer.js
Labels: testing

#29 Refactor/router
  cypress/e2e/movie_deatils_spec.cy.js
  package-lock.json
  package.json
  src/components/App/App.css
  src/components/App/App.js
  src/components/Card/Card.js
  src/components/Details/Details.css
  src/components/Details/Details.js
  src/components/Error/Error.css
  src/components/Error/Error.js
  src/index.js
  src/scratch.js
Labels: refactor

#33 Feature/accessibility
  src/components/App/App.js
  src/components/Card/Card.js
  src/components/Details/Details.css
  src/components/Details/Details.js
  src/components/MoviesCardsContainer/MoviesCardsContainer.css
  src/components/MoviesCardsContainer/MoviesCardsContainer.js
Labels: accessibility

#38 Add the cleaning of data for all movies
  src/apiCalls.js
  src/components/App/App.js
  src/components/Card/Card.js
  src/components/MoviesCardsContainer/MoviesCardsContainer.js
  src/utilities.js
Labels: refactor

#39 Refactor/clean up comments and consoles
  cypress/e2e/all_movies_spec.cy.js
  cypress/e2e/movie_details_spec.cy.js
  cypress/fixtures/example.json
  src/apiCalls.js
  src/components/App/App.css
  src/components/App/App.js
  src/components/Details/Details.css
  src/components/Details/Details.js
  src/components/Error/Error.js
  src/components/MoviesCardsContainer/MoviesCardsContainer.css
  src/components/MoviesCardsContainer/MoviesCardsContainer.js
  src/movieData.js
  src/scratch.js
  src/utilities.js
Labels: refactor

#41 Feature/search
  cypress/e2e/all_movies_spec.cy.js
  cypress/e2e/movie_details_spec.cy.js
  cypress/fixtures/money_plane.json
  cypress/fixtures/movies.json
  src/components/App/App.js
  src/components/Details/Details.js
  src/components/Form/Form.css
  src/components/Form/Form.js
  src/components/MoviesCardsContainer/MoviesCardsContainer.css
  src/components/MoviesCardsContainer/MoviesCardsContainer.js
Labels: enhancement
